import { getSql } from "../../../../packages/db/src/index.js";
export async function listCustomersWithHistory(input:{limit?:number;offset?:number;query?:string}={}){const sql=getSql();const limit=Math.min(Math.max(input.limit??100,1),200),offset=Math.max(input.offset??0,0),query=input.query?.trim()??"";const pattern=`%${query}%`;const rows=await sql`
SELECT c.id,c.first_name AS "firstName",c.last_name AS "lastName",c.email,c.phone,
 (SELECT count(*)::int FROM moms_ops.vehicles v WHERE v.customer_id=c.id) AS "vehicleCount",
 (SELECT count(*)::int FROM moms_ops.bookings b WHERE b.customer_id=c.id) AS "appointmentCount",
 (SELECT count(*)::int FROM moms_ops.service_orders so WHERE so.customer_id=c.id) AS "serviceOrderCount",
 (SELECT count(*)::int FROM moms_ops.invoices i WHERE i.customer_id=c.id) AS "invoiceCount",
 COALESCE((SELECT sum(p.amount_cents) FROM moms_ops.payments p LEFT JOIN moms_ops.bookings b ON b.id=p.booking_id LEFT JOIN moms_ops.invoices i ON i.id=p.invoice_id WHERE p.status IN ('paid','succeeded') AND (b.customer_id=c.id OR i.customer_id=c.id)),0)::int AS "totalPaidCents"
FROM moms_ops.customers c
WHERE (${query}='' OR c.first_name ILIKE ${pattern} OR c.last_name ILIKE ${pattern} OR c.email ILIKE ${pattern} OR c.phone ILIKE ${pattern})
ORDER BY c.last_name,c.first_name,c.id
LIMIT ${limit} OFFSET ${offset}`;const count=await sql`SELECT count(*)::int AS total FROM moms_ops.customers c WHERE (${query}='' OR c.first_name ILIKE ${pattern} OR c.last_name ILIKE ${pattern} OR c.email ILIKE ${pattern} OR c.phone ILIKE ${pattern})`;return {customers:rows,total:Number(count[0]?.total??0),limit,offset};}
export async function getCustomerHistory(id:string){const sql=getSql();const c=await sql`SELECT id,first_name AS "firstName",last_name AS "lastName",email,phone,address_line_1 AS "addressLine1",city,state,postal_code AS "postalCode" FROM moms_ops.customers WHERE id=${id}::uuid`;if(!c[0])return null;const vehicles=await sql`SELECT id,vin,year,make,model,engine,notes FROM moms_ops.vehicles WHERE customer_id=${id}::uuid ORDER BY year DESC,make,model`;const appointments=await sql`SELECT id,status,scheduled_start AS "scheduledStart",scheduled_end AS "scheduledEnd",service_address_line_1 AS "serviceAddressLine1",service_city AS "serviceCity",service_state AS "serviceState",quoted_total_cents AS "quotedTotalCents",notes FROM moms_ops.bookings WHERE customer_id=${id}::uuid ORDER BY scheduled_start DESC`;const orders=await sql`SELECT so.id,so.appointment_id AS "appointmentId",so.vehicle_id AS "vehicleId",so.status,so.started_at AS "startedAt",so.completed_at AS "completedAt",so.notes,v.year,v.make,v.model FROM moms_ops.service_orders so JOIN moms_ops.vehicles v ON v.id=so.vehicle_id WHERE so.customer_id=${id}::uuid ORDER BY so.created_at DESC`;const invoices=await sql`SELECT id,appointment_id AS "appointmentId",status,total_cents AS "totalCents",amount_paid_cents AS "amountPaidCents",amount_due_cents AS "amountDueCents",issued_at AS "issuedAt",paid_at AS "paidAt" FROM moms_ops.invoices WHERE customer_id=${id}::uuid ORDER BY created_at DESC`;const payments=await sql`SELECT p.id,p.booking_id AS "appointmentId",p.invoice_id AS "invoiceId",p.status,p.amount_cents AS "amountCents",p.currency,p.paid_at AS "paidAt" FROM moms_ops.payments p LEFT JOIN moms_ops.bookings b ON b.id=p.booking_id LEFT JOIN moms_ops.invoices i ON i.id=p.invoice_id WHERE b.customer_id=${id}::uuid OR i.customer_id=${id}::uuid ORDER BY p.created_at DESC`;return {customer:c[0],vehicles,appointments,serviceOrders:orders,invoices,payments};}
export async function listVehiclesWithHistory(input:{limit?:number;offset?:number;query?:string}={}){const sql=getSql();const limit=Math.min(Math.max(input.limit??100,1),200),offset=Math.max(input.offset??0,0),query=input.query?.trim()??"",pattern=`%${query}%`;const vehicles=await sql`SELECT v.id,v.year,v.make,v.model,v.engine,v.vin,c.id AS "customerId",c.first_name AS "customerFirstName",c.last_name AS "customerLastName",(SELECT count(DISTINCT bj.booking_id)::int FROM moms_ops.booking_jobs bj WHERE bj.vehicle_id=v.id) AS "appointmentCount",(SELECT count(*)::int FROM moms_ops.service_orders so WHERE so.vehicle_id=v.id) AS "serviceOrderCount",GREATEST((SELECT max(so.completed_at) FROM moms_ops.service_orders so WHERE so.vehicle_id=v.id),(SELECT max(b.scheduled_start) FROM moms_ops.booking_jobs bj JOIN moms_ops.bookings b ON b.id=bj.booking_id WHERE bj.vehicle_id=v.id)) AS "lastServiceAt" FROM moms_ops.vehicles v JOIN moms_ops.customers c ON c.id=v.customer_id WHERE (${query}='' OR v.make ILIKE ${pattern} OR v.model ILIKE ${pattern} OR COALESCE(v.vin,'') ILIKE ${pattern} OR c.first_name ILIKE ${pattern} OR c.last_name ILIKE ${pattern}) ORDER BY "lastServiceAt" DESC NULLS LAST,v.created_at DESC,v.id LIMIT ${limit} OFFSET ${offset}`;const count=await sql`SELECT count(*)::int total FROM moms_ops.vehicles v JOIN moms_ops.customers c ON c.id=v.customer_id WHERE (${query}='' OR v.make ILIKE ${pattern} OR v.model ILIKE ${pattern} OR COALESCE(v.vin,'') ILIKE ${pattern} OR c.first_name ILIKE ${pattern} OR c.last_name ILIKE ${pattern})`;return {vehicles,total:Number(count[0]?.total??0),limit,offset};}
export async function getVehicleHistory(id:string){const sql=getSql();const v=await sql`SELECT v.id,v.vin,v.year,v.make,v.model,v.engine,v.notes,c.id AS "customerId",c.first_name AS "customerFirstName",c.last_name AS "customerLastName" FROM moms_ops.vehicles v JOIN moms_ops.customers c ON c.id=v.customer_id WHERE v.id=${id}::uuid`;if(!v[0])return null;const appointments=await sql`SELECT b.id,b.status,b.scheduled_start AS "scheduledStart",b.quoted_total_cents AS "quotedTotalCents" FROM moms_ops.bookings b JOIN moms_ops.booking_jobs bj ON bj.booking_id=b.id WHERE bj.vehicle_id=${id}::uuid ORDER BY b.scheduled_start DESC`;const orders=await sql`SELECT so.id,so.appointment_id AS "appointmentId",so.status,so.started_at AS "startedAt",so.completed_at AS "completedAt",so.notes,COALESCE(json_agg(json_build_object('id',soi.id,'description',soi.description,'quantity',soi.quantity,'totalCents',soi.total_cents,'status',soi.status) ORDER BY soi.position) FILTER(WHERE soi.id IS NOT NULL),'[]'::json) items FROM moms_ops.service_orders so LEFT JOIN moms_ops.service_order_items soi ON soi.service_order_id=so.id WHERE so.vehicle_id=${id}::uuid GROUP BY so.id ORDER BY so.created_at DESC`;return {vehicle:v[0],appointments,serviceOrders:orders};}