import { getSql } from "../../../../packages/db/src/index.js";
export async function listCustomersWithHistory(){const sql=getSql();return sql`
SELECT c.id,c.first_name AS "firstName",c.last_name AS "lastName",c.email,c.phone,
 count(DISTINCT v.id)::int AS "vehicleCount",count(DISTINCT b.id)::int AS "appointmentCount",
 count(DISTINCT so.id)::int AS "serviceOrderCount",count(DISTINCT i.id)::int AS "invoiceCount",
 COALESCE(sum(DISTINCT i.total_cents),0)::int AS "invoicedCents"
FROM moms_ops.customers c LEFT JOIN moms_ops.vehicles v ON v.customer_id=c.id
LEFT JOIN moms_ops.bookings b ON b.customer_id=c.id LEFT JOIN moms_ops.service_orders so ON so.customer_id=c.id
LEFT JOIN moms_ops.invoices i ON i.customer_id=c.id GROUP BY c.id ORDER BY c.last_name,c.first_name`;}
export async function getCustomerHistory(id:string){const sql=getSql();const c=await sql`SELECT id,first_name AS "firstName",last_name AS "lastName",email,phone,address_line_1 AS "addressLine1",city,state,postal_code AS "postalCode" FROM moms_ops.customers WHERE id=${id}::uuid`;if(!c[0])return null;const vehicles=await sql`SELECT id,vin,year,make,model,engine,notes FROM moms_ops.vehicles WHERE customer_id=${id}::uuid ORDER BY year DESC,make,model`;const appointments=await sql`SELECT id,status,scheduled_start AS "scheduledStart",scheduled_end AS "scheduledEnd",service_address_line_1 AS "serviceAddressLine1",service_city AS "serviceCity",service_state AS "serviceState",quoted_total_cents AS "quotedTotalCents",notes FROM moms_ops.bookings WHERE customer_id=${id}::uuid ORDER BY scheduled_start DESC`;const orders=await sql`SELECT so.id,so.appointment_id AS "appointmentId",so.vehicle_id AS "vehicleId",so.status,so.started_at AS "startedAt",so.completed_at AS "completedAt",so.notes,v.year,v.make,v.model FROM moms_ops.service_orders so JOIN moms_ops.vehicles v ON v.id=so.vehicle_id WHERE so.customer_id=${id}::uuid ORDER BY so.created_at DESC`;const invoices=await sql`SELECT id,appointment_id AS "appointmentId",status,total_cents AS "totalCents",amount_paid_cents AS "amountPaidCents",amount_due_cents AS "amountDueCents",issued_at AS "issuedAt",paid_at AS "paidAt" FROM moms_ops.invoices WHERE customer_id=${id}::uuid ORDER BY created_at DESC`;const payments=await sql`SELECT p.id,p.booking_id AS "appointmentId",p.invoice_id AS "invoiceId",p.status,p.amount_cents AS "amountCents",p.currency,p.paid_at AS "paidAt" FROM moms_ops.payments p LEFT JOIN moms_ops.bookings b ON b.id=p.booking_id LEFT JOIN moms_ops.invoices i ON i.id=p.invoice_id WHERE b.customer_id=${id}::uuid OR i.customer_id=${id}::uuid ORDER BY p.created_at DESC`;return {customer:c[0],vehicles,appointments,serviceOrders:orders,invoices,payments};}
export async function listVehiclesWithHistory(){const sql=getSql();return sql`SELECT v.id,v.year,v.make,v.model,v.engine,v.vin,c.id AS "customerId",c.first_name AS "customerFirstName",c.last_name AS "customerLastName",count(DISTINCT b.id)::int AS "appointmentCount",count(DISTINCT so.id)::int AS "serviceOrderCount",max(COALESCE(so.completed_at,b.scheduled_start)) AS "lastServiceAt" FROM moms_ops.vehicles v JOIN moms_ops.customers c ON c.id=v.customer_id LEFT JOIN moms_ops.booking_jobs bj ON bj.vehicle_id=v.id LEFT JOIN moms_ops.bookings b ON b.id=bj.booking_id LEFT JOIN moms_ops.service_orders so ON so.vehicle_id=v.id GROUP BY v.id,c.id ORDER BY "lastServiceAt" DESC NULLS LAST,v.created_at DESC`;}
export async function getVehicleHistory(id:string){const sql=getSql();const v=await sql`SELECT v.id,v.vin,v.year,v.make,v.model,v.engine,v.notes,c.id AS "customerId",c.first_name AS "customerFirstName",c.last_name AS "customerLastName" FROM moms_ops.vehicles v JOIN moms_ops.customers c ON c.id=v.customer_id WHERE v.id=${id}::uuid`;if(!v[0])return null;const appointments=await sql`SELECT b.id,b.status,b.scheduled_start AS "scheduledStart",b.quoted_total_cents AS "quotedTotalCents" FROM moms_ops.bookings b JOIN moms_ops.booking_jobs bj ON bj.booking_id=b.id WHERE bj.vehicle_id=${id}::uuid ORDER BY b.scheduled_start DESC`;const orders=await sql`SELECT so.id,so.appointment_id AS "appointmentId",so.status,so.started_at AS "startedAt",so.completed_at AS "completedAt",so.notes,COALESCE(json_agg(json_build_object('id',soi.id,'description',soi.description,'quantity',soi.quantity,'totalCents',soi.total_cents,'status',soi.status) ORDER BY soi.position) FILTER(WHERE soi.id IS NOT NULL),'[]'::json) items FROM moms_ops.service_orders so LEFT JOIN moms_ops.service_order_items soi ON soi.service_order_id=so.id WHERE so.vehicle_id=${id}::uuid GROUP BY so.id ORDER BY so.created_at DESC`;return {vehicle:v[0],appointments,serviceOrders:orders};}